[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"

[env]
  [env.production]
    NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200